---
# Base installer values
ohs_version_folder: 12.1.3  # we can derive this later
# oracle_rsp_filename: "install_{{ oracle_family }}R2.rsp.j2"
base_version: 12.1.3.0.0
base_installer: fmw_12.1.3.0.0_ohs_linux64.bin
# base_installer_path: "OHS/{{ ohs_version }}/{{ oracle_rsp_filename }}"
base_installer_path: "OHS/12.1.3/fmw_12.1.3.0.0_ohs_linux64.bin"
# Patches information
ohs_version: 12.2.1.4.210324
patches:
  - filename: "OHS/{{ ohs_version_folder }}/p31046788_121300_Linux-x86-64.zip"
    number: 31046788
# Add OPatch values when bundled OPatch needs to be upgraded
opatch_filename: "{{ ohs_version_folder }}/p28186730_139426_Generic.zip"
opatch_filename_path: "OHS/{{ opatch_filename }}"
opatch_version: 13.9.4.2.6
opatch_folder: 6880880

# Full jdk is needed to update OPatch
java_zip_path: 'Java/jdk-8u251-linux-x64.tar.gz'
java_version_path: 'jdk1.8.0_251'
jdk_folder: "{{ ohs_home }}/oracle_common/jdk"

template_jar: "ohs_standalone_template_12.1.3.jar"
