---
liberty_fp_path: WLP/25.0.0.12-WS-LIBERTY-ND-FP.zip
liberty_installers_path: WLP/was.repo.16002.liberty.nd.zip
liberty_pid: 25.0.12.20251117_0302
jdk_version: 21.0
jdk_installation_way: unzip
liberty_java_zip_path: Java/IBM/ibm-semeru-open-jdk_x64_linux_21.0.9_10_openj9-0.56.0.tar.gz
