---
liberty_fp_path: WLP/25.0.0.9-WS-LIBERTY-ND-FP.zip
liberty_installers_path: WLP/was.repo.16002.liberty.nd.zip
liberty_pid: 25.0.9.20250821_1629
jdk_version: 21.0
jdk_installation_way: unzip
liberty_java_zip_path: Java/IBM/ibm-semeru-open-jdk_x64_linux_21.0.8_9_openj9-0.53.0.tar.gz
