---
ihs_base_path: WAS/9.0.5ND
ihs_base_archive_list:
  - was.repo.90500.ihs.zip
  - was.repo.90500.plugins.zip
  - was.repo.90500.wct.zip

ihs_fp_path: WAS/9.0.5Fixpacks
ihs_fp_archive_list:
  - 9.0.5-WS-IHSPLG-FP008.zip
  - 9.0.5-WS-WCT-FP008.zip

ihs_pid: v90_9.0.5008.20210525_1601
ihs_java_zip_path: Java/IBM/ibm-java-sdk-8.0-6.26-linux-x64-installmgr.zip
ihs_java_pid: com.ibm.java.jdk.v8
