---
base_install_file: 'fmw_12.1.3.0.0_wls.jar'
weblogic_version: 12.1
# 13.9.4.2.6
opatch: 'p28186730_139426_Generic.zip'
opatch_version: 13.9.4.2.6
# 31656851 WLS PATCH SET UPDATE 12.1.3.0.201020
patch: 'p32832660_121300_Generic.zip'
patch_number: 32832660
napply: false
patch_folder: '32832660'
java_zip_path: 'Java/jdk-8u191-linux-x64.tar.gz'
java_version_path: 'jdk1.8.0_191'
