---
base_install_file: 'fmw_14.1.1.0.0_wls.jar'
weblogic_version: 14.1
opatch: 'p28186730_139426_Generic.zip'
opatch_version: 13.9.4.2.6
patch: 'p33125254_141100_Generic.zip'
patch_number: 33069656
napply: true
patch_folder: 'WLS_SPB_14.1.1.0.210716'
java_archive_file: jdk-8u251-linux-x64.tar.gz
java_version_path: 'jdk1.8.0_251'
