---
instance_id: inst1
instance_port: 50000

db2_install_path: /opt/IBM/db2
db2_version: 12.1.0.0
db2_product: DB2_SERVER_EDITION
db2_bypass_prereq_check: false
db2_activate: True

db2_db_create: True
db2_db_name: DATABASE
db2_db_username: db2admin
db2_db_groupname: db2iadm1
db2_db_password: db2admin
db2_fenced_username: db2fenc1
db2_fenced_groupname: db2fadm1

db2_db_spm_enc: dummyPassword
db2_db_drop_required: False

bootstrap_dateformat: 'dd MM yyyy'
bootstrap_dateseparator: '/'
bootstrap_dmx_locale: 'en_US'

# Common
profiled_path: /opt/profile.d
# Server info for downloading installers / licenses directly, leave blank to copy
download_url:   # e.g. https://artifactory/repo
download_header:  # e.g. X-JFrog-Art-Api: "{{ lookup('env', 'MYTOKEN') }}"
