---
# iim
iim_install_path: /opt/IBM/InstallationManager
# websphere
websphere_install_path: /opt/IBM/WebSphere/AppServer
websphere_version: 9.0.5.18
security_username: websphere
# use encrypted password
security_password: dummypassword
# Common
profiled_path: /opt/profile.d
# Server info for downloading installers / repos directly, leave blank to copy
download_url:   # e.g. https://artifactory/repo
download_header:  # e.g. X-JFrog-Art-Api: "{{ lookup('env', 'MYTOKEN') }}"
