---
iim_install_path: /opt/IBM/InstallationManager

ihs_install_path: /opt/IBM/HTTPServer
plg_install_path: /opt/IBM/WebSphere/Plugins
wct_install_path: /opt/IBM/WebSphere/Toolbox

ihs_version: 9.0.5.22

ihs_config_type: local_distributed
ihs_admin_user: wasadmin
ihs_admin_pass: wasadmin

# Common
profiled_path: /opt/profile.d

# Server info for downloading installers / repos directly, leave blank to copy
download_url:   # e.g. https://artifactory/repo
download_header:  # e.g. X-JFrog-Art-Api: "{{ lookup('env', 'MYTOKEN') }}"
