---
- name: Check if Ant binaries exist
  stat:
    path: "{{ ant_base_path }}/apache-ant-{{ ant_version }}/bin/ant"
  register: ant_check

- name: Check Ant version
  command: "grep -e '^  <version>{{ ant_version }}</version>' {{ ant_base_path }}/apache-ant-{{ ant_version }}/lib/ant.pom"
  ignore_errors: yes
  changed_when: false
  when: ant_check.stat.exists
  register: ant_version_check

- name: Install
  when: not ant_check.stat.exists or ant_version not in ant_version_check.stdout
  block:
    - name: Create base dir
      file:
        path: "{{ ant_base_path }}"
        state: directory

    - name: Install unzip
      package:
        name: unzip
        state: present

    - name: Download Apache Ant
      get_url:
        dest: "{{ ant_base_path }}/apache-ant-current-bin.zip"
        url: "{{ artifactory_url }}/{{ artifactory_repo }}/SoftwareInstallers/Ant/apache-ant-{{ ant_version }}-bin.zip"
        mode: 0644
        headers:
          X-JFrog-Art-Api: "{{ artifactory_token }}"

    - name: Extract Apache Ant
      unarchive:
        src: "{{ ant_base_path }}/apache-ant-current-bin.zip"
        remote_src: yes
        dest: "{{ ant_base_path }}"

- name: "Create {{ profiled_path }}"
  file:
    path: "{{ profiled_path }}"
    mode: 0755
    state: directory

- name: "Create {{ profiled_path }}/ant.sh"
  template:
    dest: "{{ profiled_path }}/ant.sh"
    src: ant.sh.j2
    mode: 0755
    force: no

- name: Add extra env vars to ant.sh
  ansible.builtin.lineinfile:
    path: "{{ profiled_path }}/ant.sh"
    line: "export {{ item }}"
  loop: "{{ ant_extra_vars.split(',') | list }}"
  when: ant_extra_vars is defined

- name: Create /opt/.profile
  copy:
    dest: /opt/.profile
    content: |
      #!/bin/bash
      PATH=.:$PATH

      if [ -e {{ profiled_path }} ]; then
        if [ "$PS1" ]; then
          ls -l {{ profiled_path }}/*.sh
        fi
        for lizard in {{ profiled_path }}/*.sh ; do
          . $lizard
        done
      fi

      LANG=en_US.ISO-8859-1
      umask 002
    mode: 0755
